### ISSUE TITLE
Hi, does it return real scale model if use lidar ?

### ISSUE THREAD

**Issue by Innoyard** [KKodiac/ObjectCaptureAPIExample#1]
I have set config as..

private func initConfig() {
        captureSession = AVCaptureSession()
        
        captureSession.beginConfiguration()
        
        captureSession.sessionPreset = .photo
        
        let lidarCameraDevice = AVCaptureDevice.default(.builtInLiDARDepthCamera, for: .video, position: .back)!
        
        let format = (lidarCameraDevice.formats.last { format in
            format.formatDescription.dimensions.width == prefferedWidthResolution &&
            format.formatDescription.mediaSubType.rawValue == kCVPixelFormatType_420YpCbCr8BiPlanarFullRange &&
            !format.isVideoBinned &&
            !format.supportedDepthDataFormats.isEmpty
        })!
        
        print("format : \(format.formatDescription)")
        print("format.supportedDepthDataFormats : \(format.supportedDepthDataFormats)")
        
        let depthFormat = (format.supportedDepthDataFormats.last { depthFormat in
            depthFormat.formatDescription.mediaSubType.rawValue == kCVPixelFormatType_DepthFloat16
//            depthFormat.formatDescription.mediaSubType.rawValue == kCVPixelFormatType_DepthFloat32
        })
        
        try! lidarCameraDevice.lockForConfiguration()
        
        lidarCameraDevice.activeFormat = format
        lidarCameraDevice.activeDepthDataFormat = depthFormat
        
        lidarCameraDevice.unlockForConfiguration()
        
        let videoDeviceInput = try! AVCaptureDeviceInput(device: lidarCameraDevice)
        
        captureSession.addInput(videoDeviceInput)
        
        photoOutput = AVCapturePhotoOutput()
        captureSession.addOutput(photoOutput)
        photoOutput.isHighResolutionCaptureEnabled = true
        
        photoOutput.isDepthDataDeliveryEnabled = photoOutput.isDepthDataDeliverySupported
        print("photoOutput.isDepthDataDeliverySupported : \(photoOutput.isDepthDataDeliverySupported)")
        photoOutput.maxPhotoQualityPrioritization = .quality
        
        videoDataOutput = AVCaptureVideoDataOutput()        
        videoDataOutput.setSampleBufferDelegate(self, queue: videoQueue)
        captureSession.addOutput(videoDataOutput)
        
        depthDataOutput = AVCaptureDepthDataOutput()
        depthDataOutput.isFilteringEnabled = true
        depthDataOutput.setDelegate(self, callbackQueue: videoQueue)
        captureSession.addOutput(depthDataOutput)
        
        captureSession.commitConfiguration()
        captureSession.startRunning()
    }

and capture with.. 

        var photoSettings = AVCapturePhotoSettings()
        
        // Request HEIF photos if supported and enable high-resolution photos.
        if  self.photoOutput.availablePhotoCodecTypes.contains(.hevc) {
            photoSettings = AVCapturePhotoSettings(
                format: [AVVideoCodecKey: AVVideoCodecType.hevc])
        }
        
        // Turn on high-resolution, depth data, and quality prioritzation mode.
        photoSettings.isHighResolutionPhotoEnabled = true
        //photoSettings.isDepthDataDeliveryEnabled = self.photoOutput.isDepthDataDeliveryEnabled
        photoSettings.isDepthDataDeliveryEnabled = true
        photoSettings.photoQualityPrioritization = .quality
        photoSettings.isDepthDataFiltered = true
        
        // Request that the camera embed a depth map into the HEIC output file.
        photoSettings.embedsDepthDataInPhoto = true
        
        self.photoOutput.capturePhoto(with: photoSettings, delegate: self)

finally saved heic..

        let image_dir = self.imageDirectory!.appendingPathComponent("\(self.scanCount).HEIC")
        print("Depth Data : \(photo.depthData)")
        try! photo.fileDataRepresentation()!.write(to: image_dir,
                                                   options: .atomic)

But with this heic, when ran photogrammetry, the reconstructed model is not in real scale.

Do you know how to make the reconstructed model into real scale?

**Comment by KKodiac** [comment]
Reason for `PhotogrammetrySession` not producing up-to-scale results is mostly because photos used to produce session models do not contain depth map data(according to several Apple Developer Forum post [#1](https://developer.apple.com/forums/thread/718030), [#2](https://developer.apple.com/forums/thread/704570)). This means that HEIC images do not have the embedded depth maps and there is a possibility of your `PhotogrammetrySession` producing warning saying it will not be utilizing depth map. 

I have only tested on iPad Pro with a LiDAR sensor(forgot which version). So it might be the case of `.activeDepthFormat` not supporting you device that is causing your depth map to not be embedded in the HEIC image.

It might help you to see Apple's original [example](https://developer.apple.com/documentation/realitykit/taking_pictures_for_3d_object_capture) which uses `BuiltInDualCamera`. Or check out this year's WWDC23 session ["Meet Object Capture for iOS"](https://developer.apple.com/wwdc23/10191) which comes with full api support for capturing photo with iOS LiDAR sensor.
There is also an example I made utilizing this new support if you'd like an example.
